version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-finance-tracker
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - laravel

  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance_db         # sesuaikan
      POSTGRES_USER: finance_user     # sesuaikan
      POSTGRES_PASSWORD: finance_pass # sesuaikan
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - laravel


  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
